name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore Kubernetes.sln
    - name: Build
      run: dotnet build Kubernetes.sln --no-restore
    - name: Test
      run: dotnet test xUnitTest --no-build --verbosity normal
    -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        id: kmddeveloper/web
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
    -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
